// Maps cuisine types and dish names to local food images for rich visual cards
import dishRamen from "@/assets/dish-ramen.jpg";
import dishTacos from "@/assets/dish-tacos.jpg";
import dishButterChicken from "@/assets/dish-butter-chicken.jpg";
import dishCroissant from "@/assets/dish-croissant.jpg";
import dishPadthai from "@/assets/dish-padthai.jpg";
import dishEthiopian from "@/assets/dish-ethiopian.jpg";
import dishPizza from "@/assets/dish-pizza.jpg";
import dishCeviche from "@/assets/dish-ceviche.jpg";
import dishBibimbap from "@/assets/dish-bibimbap.jpg";
import dishKebab from "@/assets/dish-kebab.jpg";
import dishMoussaka from "@/assets/dish-moussaka.jpg";
import dishPekingDuck from "@/assets/dish-peking-duck.jpg";
import dishAsado from "@/assets/dish-asado.jpg";
import dishTagine from "@/assets/dish-tagine.jpg";
import dishPho from "@/assets/dish-pho.jpg";
import dishPaella from "@/assets/dish-paella.jpg";

// ===== NAME-BASED MATCHING (partial, case-insensitive) =====
const nameMap: Record<string, string> = {
  // Japanese
  ramen: dishRamen,
  sushi: dishRamen,
  tempura: dishRamen,
  gyoza: dishRamen,
  udon: dishRamen,
  soba: dishRamen,
  tonkatsu: dishRamen,
  okonomiyaki: dishRamen,
  takoyaki: dishRamen,
  yakitori: dishRamen,
  miso: dishRamen,
  onigiri: dishRamen,
  matcha: dishRamen,
  wagyu: dishRamen,
  kaiseki: dishRamen,
  "xiao long bao": dishPekingDuck,
  dumpling: dishPekingDuck,

  // Mexican / Latin
  tacos: dishTacos,
  "al pastor": dishTacos,
  burrito: dishTacos,
  enchilada: dishTacos,
  quesadilla: dishTacos,
  tamale: dishTacos,
  mole: dishTacos,
  guacamole: dishTacos,
  elote: dishTacos,
  chilaquile: dishTacos,
  pozole: dishTacos,
  pupusa: dishTacos,
  arepa: dishTacos,
  empanada: dishAsado,
  chimichurri: dishAsado,

  // Indian / South Asian
  "butter chicken": dishButterChicken,
  tikka: dishButterChicken,
  biryani: dishButterChicken,
  masala: dishButterChicken,
  dosa: dishButterChicken,
  curry: dishButterChicken,
  samosa: dishButterChicken,
  naan: dishButterChicken,
  paneer: dishButterChicken,
  dal: dishButterChicken,
  tandoori: dishButterChicken,
  vindaloo: dishButterChicken,
  korma: dishButterChicken,
  chana: dishButterChicken,
  "rogan josh": dishButterChicken,
  hilsa: dishButterChicken,
  momo: dishButterChicken,
  "ema datshi": dishButterChicken,
  kottu: dishButterChicken,

  // French / Pastry
  croissant: dishCroissant,
  baguette: dishCroissant,
  "crème brûlée": dishCroissant,
  bouillabaisse: dishCroissant,
  quiche: dishCroissant,
  ratatouille: dishCroissant,
  "coq au vin": dishCroissant,
  macaron: dishCroissant,
  "foie gras": dishCroissant,
  cassoulet: dishCroissant,
  crêpe: dishCroissant,
  soufflé: dishCroissant,
  éclair: dishCroissant,
  boeuf: dishCroissant,
  waffle: dishCroissant,
  moules: dishCroissant,
  frites: dishCroissant,
  stroopwafel: dishCroissant,

  // Thai / Southeast Asian
  "pad thai": dishPadthai,
  "tom yum": dishPadthai,
  "green curry": dishPadthai,
  "som tam": dishPadthai,
  "massaman": dishPadthai,
  satay: dishPadthai,
  "nasi goreng": dishPadthai,
  rendang: dishPadthai,
  laksa: dishPadthai,
  "nasi lemak": dishPadthai,
  "char kway teow": dishPadthai,
  gado: dishPadthai,
  lumpia: dishPadthai,
  adobo: dishPadthai,
  sinigang: dishPadthai,
  lechon: dishPadthai,
  amok: dishPadthai,
  "fish amok": dishPadthai,
  "babi guling": dishPadthai,

  // Ethiopian / African
  "doro wat": dishEthiopian,
  injera: dishEthiopian,
  "kitfo": dishEthiopian,
  jollof: dishEthiopian,
  fufu: dishEthiopian,
  suya: dishEthiopian,
  bobotie: dishEthiopian,
  biltong: dishEthiopian,
  bunny: dishEthiopian,
  "egusi": dishEthiopian,
  thieboudienne: dishEthiopian,
  cachupa: dishEthiopian,
  ugali: dishEthiopian,
  nyama: dishEthiopian,
  braaivleis: dishEthiopian,
  "piri piri": dishEthiopian,
  mafe: dishEthiopian,
  "palm nut": dishEthiopian,

  // Italian
  pizza: dishPizza,
  margherita: dishPizza,
  carbonara: dishPizza,
  risotto: dishPizza,
  pasta: dishPizza,
  lasagna: dishPizza,
  osso: dishPizza,
  "tiramisù": dishPizza,
  tiramisu: dishPizza,
  gelato: dishPizza,
  bruschetta: dishPizza,
  gnocchi: dishPizza,
  pesto: dishPizza,
  arancini: dishPizza,
  focaccia: dishPizza,
  prosciutto: dishPizza,
  "jamón": dishPaella,

  // Peruvian / Andean
  ceviche: dishCeviche,
  "lomo saltado": dishCeviche,
  "ají de gallina": dishCeviche,
  anticucho: dishCeviche,
  "causa": dishCeviche,
  cuy: dishCeviche,
  "bandeja paisa": dishCeviche,
  sancocho: dishCeviche,
  ajiaco: dishCeviche,

  // Korean
  bibimbap: dishBibimbap,
  kimchi: dishBibimbap,
  bulgogi: dishBibimbap,
  tteokbokki: dishBibimbap,
  "korean fried": dishBibimbap,
  japchae: dishBibimbap,
  galbi: dishBibimbap,
  samgyeopsal: dishBibimbap,
  "bingsu": dishBibimbap,

  // Turkish / Middle Eastern / Levantine
  kebab: dishKebab,
  adana: dishKebab,
  hummus: dishKebab,
  falafel: dishKebab,
  shawarma: dishKebab,
  baklava: dishKebab,
  lahmacun: dishKebab,
  dolma: dishKebab,
  börek: dishKebab,
  borek: dishKebab,
  "iskender": dishKebab,
  kibbeh: dishKebab,
  tabbouleh: dishKebab,
  fattoush: dishKebab,
  manakish: dishKebab,
  mansaf: dishKebab,
  kabsa: dishKebab,
  machboos: dishKebab,
  "al harees": dishKebab,
  "kunafeh": dishKebab,
  knafeh: dishKebab,
  mandi: dishKebab,
  luqaimat: dishKebab,
  koshari: dishKebab,
  "ful medames": dishKebab,
  shakshuka: dishKebab,
  musakhan: dishKebab,

  // Greek / Mediterranean
  moussaka: dishMoussaka,
  souvlaki: dishMoussaka,
  gyro: dishMoussaka,
  spanakopita: dishMoussaka,
  tzatziki: dishMoussaka,
  halloumi: dishMoussaka,
  kleftiko: dishMoussaka,
  pastitsio: dishMoussaka,
  "saganaki": dishMoussaka,
  "imam bayildi": dishMoussaka,

  // Chinese
  "peking duck": dishPekingDuck,
  "dim sum": dishPekingDuck,
  "kung pao": dishPekingDuck,
  wonton: dishPekingDuck,
  "mapo tofu": dishPekingDuck,
  "char siu": dishPekingDuck,
  "dan dan": dishPekingDuck,
  congee: dishPekingDuck,
  "hot pot": dishPekingDuck,
  hotpot: dishPekingDuck,
  jiaozi: dishPekingDuck,
  "spring roll": dishPekingDuck,
  "fried rice": dishPekingDuck,
  chow: dishPekingDuck,
  "sichuan": dishPekingDuck,
  "hong shao": dishPekingDuck,
  "dongpo": dishPekingDuck,
  "lion's head": dishPekingDuck,
  "zha jiang": dishPekingDuck,

  // Argentine / South American grilled
  asado: dishAsado,
  churrasco: dishAsado,
  feijoada: dishAsado,
  "pão de queijo": dishAsado,
  "açaí": dishAsado,
  moqueca: dishAsado,
  coxinha: dishAsado,
  pastel: dishAsado,
  milanesa: dishAsado,
  choripan: dishAsado,
  locro: dishAsado,
  curanto: dishAsado,
  cevapi: dishAsado,
  pljeskavica: dishAsado,

  // Moroccan / North African
  tagine: dishTagine,
  couscous: dishTagine,
  pastilla: dishTagine,
  harira: dishTagine,
  "b'stilla": dishTagine,
  merguez: dishTagine,
  mechoui: dishTagine,
  // shakshuka already mapped above
  msemen: dishTagine,

  // Vietnamese
  pho: dishPho,
  "phở": dishPho,
  "banh mi": dishPho,
  "bún chả": dishPho,
  "bun cha": dishPho,
  "gỏi cuốn": dishPho,
  "spring rolls": dishPho,
  "cà phê": dishPho,
  "cao lầu": dishPho,
  "com tam": dishPho,

  // Spanish
  paella: dishPaella,
  tapas: dishPaella,
  gazpacho: dishPaella,
  churros: dishPaella,
  tortilla: dishPaella,
  pintxos: dishPaella,
  patatas: dishPaella,
  croquetas: dishPaella,
  "crema catalana": dishPaella,

  // Georgian
  khachapuri: dishKebab,
  khinkali: dishKebab,

  // Eastern European / Nordic / Baltic
  pierogi: dishMoussaka,
  borscht: dishMoussaka,
  goulash: dishMoussaka,
  schnitzel: dishMoussaka,
  "wiener": dishMoussaka,
  sauerkraut: dishMoussaka,
  bratwurst: dishMoussaka,
  pretzel: dishMoussaka,
  strudel: dishMoussaka,
  svíčková: dishMoussaka,
  trdelník: dishMoussaka,
  "smørrebrød": dishCroissant,
  smorgasbord: dishCroissant,
  gravlax: dishCroissant,
  "köttbullar": dishCroissant,
  meatball: dishCroissant,
  poutine: dishCroissant,

  // Caribbean
  "jerk chicken": dishTacos,
  jerk: dishTacos,
  ackee: dishTacos,
  plantain: dishTacos,
  "rice and peas": dishTacos,
  roti: dishButterChicken,
  doubles: dishButterChicken,

  // Pacific / Oceanian
  "meat pie": dishAsado,
  "pavlova": dishCroissant,
  lamington: dishCroissant,
  hangi: dishAsado,
  laulau: dishPadthai,
  poke: dishRamen,
  "fish and chips": dishCroissant,
};

// ===== CUISINE-TYPE FALLBACK (matches against cuisine_type from DB) =====
const cuisineMap: Record<string, string> = {
  // Major cuisines
  japanese: dishRamen,
  mexican: dishTacos,
  indian: dishButterChicken,
  french: dishCroissant,
  thai: dishPadthai,
  ethiopian: dishEthiopian,
  italian: dishPizza,
  peruvian: dishCeviche,
  korean: dishBibimbap,
  turkish: dishKebab,
  greek: dishMoussaka,
  chinese: dishPekingDuck,
  argentine: dishAsado,
  moroccan: dishTagine,
  vietnamese: dishPho,
  spanish: dishPaella,

  // Middle East & Central Asia
  lebanese: dishKebab,
  middle_eastern: dishKebab,
  iraqi: dishKebab,
  iranian: dishKebab,
  persian: dishKebab,
  syrian: dishKebab,
  palestinian: dishKebab,
  jordanian: dishKebab,
  emirati: dishKebab,
  gulf: dishKebab,
  saudi: dishKebab,
  yemeni: dishKebab,
  omani: dishKebab,
  kuwaiti: dishKebab,
  bahraini: dishKebab,
  qatari: dishKebab,
  afghan: dishKebab,
  uzbek: dishKebab,
  "central asian": dishKebab,
  azerbaijani: dishKebab,
  armenian: dishKebab,
  georgian: dishKebab,
  kazakh: dishKebab,
  turkmen: dishKebab,
  kyrgyz: dishKebab,
  tajik: dishKebab,

  // South Asia
  bangladeshi: dishButterChicken,
  pakistani: dishButterChicken,
  sri_lankan: dishButterChicken,
  "sri lankan": dishButterChicken,
  nepali: dishButterChicken,
  bhutanese: dishButterChicken,
  maldivian: dishButterChicken,

  // Southeast Asia
  indonesian: dishPadthai,
  filipino: dishPadthai,
  malaysian: dishPadthai,
  singaporean: dishPadthai,
  cambodian: dishPadthai,
  burmese: dishPadthai,
  myanmar: dishPadthai,
  laotian: dishPadthai,
  "southeast asian": dishPadthai,
  bruneian: dishPadthai,
  timorese: dishPadthai,

  // East Asia
  shanghainese: dishPekingDuck,
  cantonese: dishPekingDuck,
  sichuan: dishPekingDuck,
  taiwanese: dishPekingDuck,
  mongolian: dishPekingDuck,
  "hong kong": dishPekingDuck,

  // Americas
  brazilian: dishAsado,
  colombian: dishCeviche,
  ecuadorian: dishCeviche,
  chilean: dishCeviche,
  bolivian: dishCeviche,
  venezuelan: dishCeviche,
  paraguayan: dishAsado,
  uruguayan: dishAsado,
  cuban: dishTacos,
  dominican: dishTacos,
  "costa rican": dishTacos,
  salvadoran: dishTacos,
  guatemalan: dishTacos,
  honduran: dishTacos,
  nicaraguan: dishTacos,
  panamanian: dishTacos,
  caribbean: dishTacos,
  jamaican: dishTacos,
  haitian: dishTacos,
  trinidadian: dishTacos,
  "central american": dishTacos,
  bahamian: dishTacos,
  bajan: dishTacos,
  guyanese: dishTacos,
  belizean: dishTacos,
  surinamese: dishTacos,
  canadian: dishCroissant,
  american: dishAsado,

  // Europe
  british: dishCroissant,
  german: dishMoussaka,
  portuguese: dishPaella,
  belgian: dishCroissant,
  dutch: dishCroissant,
  swiss: dishCroissant,
  austrian: dishMoussaka,
  hungarian: dishMoussaka,
  "central european": dishMoussaka,
  polish: dishMoussaka,
  czech: dishMoussaka,
  slovak: dishMoussaka,
  romanian: dishMoussaka,
  bulgarian: dishMoussaka,
  serbian: dishAsado,
  croatian: dishMoussaka,
  bosnian: dishKebab,
  slovenian: dishMoussaka,
  albanian: dishMoussaka,
  montenegrin: dishMoussaka,
  macedonian: dishMoussaka,
  kosovar: dishKebab,
  "eastern european": dishMoussaka,
  russian: dishMoussaka,
  ukrainian: dishMoussaka,
  belarusian: dishMoussaka,
  moldovan: dishMoussaka,
  baltic: dishCroissant,
  estonian: dishCroissant,
  latvian: dishCroissant,
  lithuanian: dishCroissant,
  finnish: dishCroissant,
  swedish: dishCroissant,
  norwegian: dishCroissant,
  danish: dishCroissant,
  icelandic: dishCroissant,
  nordic: dishCroissant,
  irish: dishCroissant,
  scottish: dishCroissant,
  catalan: dishPaella,
  basque: dishPaella,
  mediterranean: dishMoussaka,
  cypriot: dishMoussaka,
  maltese: dishMoussaka,

  // Africa
  nigerian: dishEthiopian,
  ghanaian: dishEthiopian,
  senegalese: dishEthiopian,
  "south african": dishEthiopian,
  kenyan: dishEthiopian,
  tanzanian: dishEthiopian,
  ugandan: dishEthiopian,
  rwandan: dishEthiopian,
  congolese: dishEthiopian,
  cameroonian: dishEthiopian,
  ivorian: dishEthiopian,
  "west african": dishEthiopian,
  "east african": dishEthiopian,
  "north african": dishTagine,
  "central african": dishEthiopian,
  "southern african": dishEthiopian,
  algerian: dishTagine,
  tunisian: dishTagine,
  libyan: dishTagine,
  egyptian: dishKebab,
  sudanese: dishEthiopian,
  somali: dishEthiopian,
  eritrean: dishEthiopian,
  djiboutian: dishEthiopian,
  malian: dishEthiopian,
  burkinabè: dishEthiopian,
  beninese: dishEthiopian,
  togolese: dishEthiopian,
  nigerien: dishEthiopian,
  "cape verdean": dishEthiopian,
  angolan: dishEthiopian,
  mozambican: dishEthiopian,
  zimbabwean: dishEthiopian,
  zambian: dishEthiopian,
  malagasy: dishEthiopian,
  mauritian: dishEthiopian,
  saharan: dishTagine,
  "indian ocean": dishPadthai,
  swazi: dishEthiopian,
  gambian: dishEthiopian,
  guinean: dishEthiopian,
  "sierra leonean": dishEthiopian,
  liberian: dishEthiopian,
  chadian: dishEthiopian,
  burundian: dishEthiopian,
  gabonese: dishEthiopian,
  equatoguinean: dishEthiopian,

  // Oceania
  australian: dishAsado,
  "new zealand": dishAsado,
  pacific: dishPadthai,
  fijian: dishPadthai,
  samoan: dishPadthai,
  tongan: dishPadthai,
  polynesian: dishPadthai,
  melanesian: dishPadthai,
  hawaiian: dishRamen,
  "papua new guinean": dishPadthai,
};

// Gradient fallbacks by continent for dishes without images
export const continentGradients: Record<string, string> = {
  Asia: "from-amber-900 via-orange-800 to-yellow-900",
  Europe: "from-rose-900 via-burgundy to-slate-800",
  Americas: "from-emerald-900 via-teal-800 to-cyan-900",
  Africa: "from-orange-900 via-amber-800 to-yellow-800",
  Oceania: "from-purple-900 via-indigo-800 to-blue-900",
  "North America": "from-blue-900 via-slate-800 to-indigo-900",
  "South America": "from-emerald-900 via-teal-800 to-cyan-900",
};

export function getDishImage(dishName: string, cuisineType: string): string | null {
  const lowerName = dishName.toLowerCase();

  // Try name-based match first
  for (const [key, img] of Object.entries(nameMap)) {
    if (lowerName.includes(key)) return img;
  }

  // Try cuisine-type match
  const lowerCuisine = cuisineType.toLowerCase().replace(/[_-]/g, " ");
  for (const [key, img] of Object.entries(cuisineMap)) {
    const normalizedKey = key.replace(/[_-]/g, " ");
    if (lowerCuisine.includes(normalizedKey)) return img;
  }

  return null;
}

// Get all images as an array for cycling through
export const allDishImages = [
  dishRamen, dishTacos, dishButterChicken, dishCroissant,
  dishPadthai, dishEthiopian, dishPizza, dishCeviche,
  dishBibimbap, dishKebab, dishMoussaka, dishPekingDuck,
  dishAsado, dishTagine, dishPho, dishPaella,
];
